#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m                                                                      \033[0m"
echo -e "\033[1;34m                      | |   (_)_ __  _   ___  __                      \033[0m" 
echo -e "\033[1;34m                      | |   | | '_ \| | | \ \/ /                      \033[0m" 
echo -e "\033[1;34m                      | |___| | | | | |_| |>  <                       \033[0m" 
echo -e "\033[1;34m                      |_____|_|_| |_|\____/_/\_\                      \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

sleep 5

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "INSTALANDO PACKSSH" ; tput sgr0
echo -e "\033[1;34m INSTALANDO...\033[1;32m"

apt-get install htop -y
apt-get update
apt-get install python-pip -y
pip install speedtest-cli

clear
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/monitorcpu -O /bin/CpuMonitor
chmod +x /bin/CpuMonitor

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/LimpadorCache -O /bin/ClearCache
chmod +x /bin/ClearCache

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/usermonitor -O /bin/UserMonitor
chmod +x /bin/UserMonitor

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/OpenUdp -O /bin/OpenUDP
chmod +x /bin/OpenUDP

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/TesteConexao -O /bin/SpeedTest
chmod +x /bin/SpeedTest

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/Banner -O /bin/Banner
chmod +x /bin/Banner

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/UserBackup -O /bin/UserBackup
chmod +x /bin/UserBackup

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/UserCreate -O /bin/UserCreate
chmod +x /bin/UserCreate

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/LimiterSSH -O /bin/LimiterSSH
chmod +x /bin/LimiterSSH

wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/PackSSH -O /bin/PackSSH
chmod +x /bin/PackSSH

clear




tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "PackSSH" ; tput sgr0
echo -e OBS:    Digite- PackSSH - para acessar sempre que precisar a essas Utilidades
echo -e "\033[01;31m=====> UserCreate (Criar Usuarios SSH)\033[0m"
echo -e "\033[01;31m=====> UserBackup (Gerencia Backup de Usuarios SSH)\033[0m"
echo -e "\033[01;31m=====> CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e "\033[01;31m=====> UserMonitor (Monitora os Usuarios Conectados)\033[0m"
echo -e "\033[01;31m=====> ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e "\033[01;31m=====> OpenUDP (Libera a porta UDP para Ligacão e jogos)\033[0m"
echo -e "\033[01;31m=====> SpeedTest (Testa a Velocidade de Link do Servidor)\033[0m"
echo -e "\033[01;31m=====> Banner (Mensagem para Usuarios Quando Conectar ao Servidor)\033[0m"
echo -e "\033[01;31m=====> LimiterSSH (Limitada as Conexoes Definidas de Cada Usuario)\033[0m"
