#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m                                                                      \033[0m"
echo -e "\033[1;37m                      | |   (_)_ __  _   ___  __                      \033[0m" 
echo -e "\033[1;37m                      | |   | | '_ \| | | \ \/ /                      \033[0m" 
echo -e "\033[1;37m                      | |___| | | | | |_| |>  <                       \033[0m" 
echo -e "\033[1;37m                      |_____|_|_| |_|\__,_/_/\_\                      \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

sleep 5

echo -e "\033[1;34m INSTALANDO PACKSSH...\033[1;32m"
sleep 2
apt-get install htop -y
clear
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/monitorcpu -O /bin/monitorcpu
chmod +x /bin/monitorcpu
sleep 2
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/LimpadorCache -O /bin/limpadorcache
chmod +x /bin/limpadorcache
