#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m                                                                      \033[0m"
echo -e "\033[1;37m                      | |   (_)_ __  _   ___  __                      \033[0m" 
echo -e "\033[1;37m                      | |   | | '_ \| | | \ \/ /                      \033[0m" 
echo -e "\033[1;37m                      | |___| | | | | |_| |>  <                       \033[0m" 
echo -e "\033[1;37m                      |_____|_|_| |_|\__,_/_/\_\                      \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

sleep 5

echo -e "\033[1;34m INSTALANDO PACKSSH...\033[1;32m"
sleep 2
apt-get install htop -y
clear
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/monitorcpu -O /bin/monitorcpu
chmod +x /bin/monitorcpu
sleep 2
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/LimpadorCache -O /bin/limpadorcache
chmod +x /bin/limpadorcache




#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi

clear
echo -e "\033[1;37m VpsPacket © Luiz Henrique \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] monitorcpu \033[1;30m(limite de conexoes simultaneas)\033[1;33m
[2] UserCreate \033[1;30m(Criar usuarios)\033[1;33m
[3] UserRedefine \033[1;30m(Opções para mudanças no usuario)\033[1;33m
[4] UserBack \033[1;30m(Deletar, Desconectar, Opções)\033[1;33m
[5] Firewall-block \033[1;30m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m
[6] ResetFirewall \033[1;30m(Retira todas as regras iptables [RISCOS])\033[1;33m
[7] Istall-addhosts \033[1;30m(Faz a preparaçao para add-host)\033[1;33m
[8] Add-host \033[1;30m(Adicionar hosts aceitos pelo squid )\033[1;33m
[9] Monitoring \033[1;30m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;33m
[10] Backup-Users \033[1;30m(Backup dos usuarios para reinstalação futura)\033[1;33m
[11] Rest-Users \033[1;30m(Restaurar usuarios feito backup)\033[1;33m
[12] Detalhes-Users \033[1;30m(Mostra informações sobre os usuarios !!)\033[1;33m
[13] Banner \033[1;30m(Banner mensagem no ssh)\033[1;33m
[14] Speedtest \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m
[15] System-Detalhes \033[1;30m(Detalhes sobre o Sistema [Created BadGuy])\033[1;33m
[16] Detalhes \033[1;30m(Detalhes sobre o VpsPack)\033[1;33m
[17] Desinstalar \033[1;30m(Remover o VpsPack)\033[0m"
read -p ": " opcao
