#!/bin/bash
export red=$'\e[0;91m'
export green=$'\e[0;92m'
export white=$'\e[0;97m'
export cyan=$'\e[1;36m'
 
function banner {
printf "${cyan}
 _   _                      ____                      _            _
| | | |___  ___ _ __ ___   / ___|___  _ __   ___  ___| |_ __ _  __| | ___  ___
| | | / __|/ _ \  __/ __| | |   / _ \|  _ \ / _ \/ __| __/ _  |/ _ |/ _ \/ __|
| |_| \__ \  __/ |  \__ \ | |__| (_) | | | |  __/ (__| || (_| | (_| | (_) \__ \
 \___/|___/\___|_|  |___/  \____\___/|_| |_|\___|\___|\__\__,_|\__,_|\___/|___/
 
${red}By PackSSH                                     
                            
"
}
 
 
while true
do
monitorar=$(ps x | grep "sshd:" | wc -l)
resultado=$(($monitorar-1))
banner
echo "${green}Usuarios Conectados: ${white}$resultado"
sleep 5s
clear
done
