#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "PackSSH" ; tput sgr0
echo -e OBS:    Digite- PackSSH - para acessar sempre que precisar a essas Utilidades
echo -e "\033[01;31m=====> UserCreate (Criar Usuarios SSH)\033[0m"
echo -e "\033[01;31m=====> UserBackup (Gerencia Backup de Usuarios SSH)\033[0m"
echo -e "\033[01;31m=====> CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e "\033[01;31m=====> UserMonitor (Monitora Os Usuarios Conectados)\033[0m"
echo -e "\033[01;31m=====> ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e "\033[01;31m=====> OpenUDP (Libera a porta UDP para Ligacão e jogos)\033[0m"
echo -e "\033[01;31m=====> SpeedTest (Testa a Velociade de Link do Servidor)\033[0m"
echo -e "\033[01;31m=====> Banner (Mensagem para Usuarios Quando Conectar ao Servidor)\033[0m"
