#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "PackSSH" ; tput sgr0
echo -e OBS:    Digite - PackSSH - para acessar esse PACK
echo -e |1| "\033[01;34m•====> ConfVPS (CONFIGURA A VPS|SQUID3|)\033[01;34m"
echo -e |2| "\033[01;31m•====> UserCreate (Criar Usuarios SSH)\033[0m"
echo -e |3| "\033[01;31m•====> UserBackup (Gerencia Backup dos Usuarios SSH)\033[0m"
echo -e |4| "\033[01;31m•====> CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e |5| "\033[01;31m•====> UserMonitor (Monitora os Usuarios Conectados)\033[0m"
echo -e |6| "\033[01;31m•====> DadosMonitor (Monitora o Uso de Dados/Banda|in||out|)\033[0m"
echo -e |7| "\033[01;31m•====> VNC (Ativa a Interface Gráfica no Servidor)\033[0m"
echo -e |8| "\033[01;31m•====> ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e |9| "\033[01;31m•====> OpenUDP (Libera a Porta UDP para Ligacão e Jogos)\033[0m"
echo -e |10| "\033[01;31m•====> SpeedTest (Testa a Velocidade de Link do Servidor)\033[0m"
echo -e |11| "\033[01;31m•====> Banner (Mensagem para Usuario Quando Conectar)\033[0m"
echo -e |12| "\033[01;31m•====> LimiterSSH (Limita as Conexoes de Cada Usuario)\033[0m"
echo -e |13| "\033[01;31m•====> MudarLimite (Muda o Limite do Usuario)\033[0m"
echo -e |14| "\033[01;31m•====> MudarSenha (Muda a Senha do Usuario)\033[0m"
echo -e |15| "\033[01;31m•====> MudarValidade (Muda a Data de Validade do Usuario)\033[0m"
echo -e |16| "\033[01;31m•====> UserDel (Deleta Usuario)\033[0m"
echo -e |17| "\033[01;31m•====> addhost (Adiciona Novo Host ao Squid)\033[0m"

read -p ": " opcao

case $opcao in
 1)
  ConfVPS;;
 2)
  UserCreate;;
 3)
  UserBackup;;
 4)
  CpuMonitor;;
 5)
  UserMonitor;;
 6)
  DadosMonitor;;
 7)
  VNC;;
 8)
  ClearCache;;
 9)
  OpenUDP;;
 10)
  SpeedTest;; 
 11)
  Banner;;
 12)
  LimiterSSH;;
 13)
  MudarLimite;;
 14)
  MudarSenha;;
 15)
  MudarValidade;;
 16)
  UserDel;;
 17)
  addhost;;
